name: Deploy Model Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "model_service/**"
      - ".github/workflows/deploy_model_service.yml"

jobs:
  deploy-model-service:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy model service to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: false
          script: |
            if [ ! -d "$HOME/nn-model" ]; then
              git clone git@github.com:noodnood-team/nn-model.git "$HOME/nn-model"
            fi
            cd "$HOME/nn-model"
            git pull origin main